language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
